//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Ecomerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class CartDetail
    {
        public string CartID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }

        public List<Product> SelectProductCartQuery(string cartId)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "select P.* from Product P where P.ProductID in" +
                    " (select cd.ProductID from Cart c, CartDetail cd where c.CartID = cd.CartID and c.CartID = '" + cartId + "')";
                SqlCommand cmd = new SqlCommand(sql, conn);

                List<Product> res = new List<Product>();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Product product = new Product();
                    product.ProductID = dr["ProductID"].ToString();
                    product.ProductName = dr["ProductName"].ToString();
                    product.ProductSize = dr["ProductSize"].ToString();
                    product.ProductUnitSize = dr["ProductUnitSize"].ToString();
                    product.ProductBrand = dr["ProductBrand"].ToString();
                    product.ProductOrigin = dr["ProductOrigin"].ToString();
                    product.ProductQuantity = Convert.ToInt32(dr["ProductQuantity"].ToString());
                    product.ProductPrice = Convert.ToDecimal(dr["ProductPrice"].ToString());
                    res.Add(product);
                }
                conn.Close();
                return res;
            }
        }

        public void AddCartDetailQuery(string cartID, string productId)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "insert into CartDetail values ('" + cartID + "', '" + productId + "', " + 0 + ")";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.ExecuteNonQuery();
            }
        }

        public void DeleteProductCartQuery(string cartId, string productId)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "delete from CartDetail where CartID = '" + cartId + "' and ProductID = '" + productId + "'";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.ExecuteNonQuery();
                conn.Close();
            }
        }

        public bool CheckProductExist(string cartId, string productId)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "select * from CartDetail where CartID = '" + cartId + "' and ProductID = '" + productId + "'";
                SqlCommand cmd = new SqlCommand(sql, conn);

                int counter = 0;
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    counter++;
                }
                conn.Close();
                return counter > 0;
            }
        }
    }
}
