//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Ecomerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class CustomerAccount
    {
        public string CustomerACID { get; set; }
        public string CustomerID { get; set; }
    
        public virtual C_User C_User { get; set; }
        public virtual UserAccount UserAccount { get; set; }

        public string GetAgentID(string username)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "select CustomerID from CustomerAccount where CustomerACID = '" + username + "' or CustomerID = '" + username + "'";
                SqlCommand cmd = new SqlCommand(sql, conn);

                SqlDataReader dr = cmd.ExecuteReader();
                string res = "";
                while (dr.Read())
                {
                    res = dr["CustomerID"].ToString();
                }
                conn.Close();
                return res;
            }
        }
    }
}
