//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Ecomerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class DeliveryCustomerReceiptDetail
    {
        public string DeliveryCustomerReceiptID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual DeliveryCustomerReceipt DeliveryCustomerReceipt { get; set; }
        public virtual Product Product { get; set; }

        public void AddReceiptDetailQuery(string receiptID, string ProductID, int ProductQuantity)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "insert into DeliveryCustomerReceiptDetail values ('" +
                    receiptID +
                    "', '" + ProductID +
                    "', " + ProductQuantity + ")";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.ExecuteNonQuery();
            }
        }
    }
}
