//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Ecomerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class UserAccount
    {
        [DisplayName("Username")]
        [Required(ErrorMessage = "Please enter your username")]
        public string UserName { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter your password")]
        public string UserPassword { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<bool> UserDeleted { get; set; }
    
        public virtual CustomerAccount CustomerAccount { get; set; }

        public string LoginMessageError { get; set; }
    }
}
